export const OPTIONS = [
  'crunch',
  'pompe',
  'traction',
  'Sit-up décliné',
  'Relevé de genoux suspendu',
  'Relevé de jambes à la chaise romaine',
  'Roulette à abdominaux',
  'Relevé de jambes suspendu',
  'Crunch à la poulie',
  'Flexions des obliques au banc à lombaire à 45°',
  'Planche latérale',
  'Mountain climber',
  'Rotations du buste avec barre',
  'Crunch sur swiss ball',
  'Rotations des abdominaux suspendu',
  'Sit-up avec médecine ball contre un mur',
  'Crunch à la machine',
  'Dragon flag',
  'Flexions latérales avec haltère',
  'AB Coaster',
  'Crunch debout avec élastique',
  'Crunch papillon',
  'Crunch bicyclette',
  'Jackknife sur swiss ball',
  'Crunch avec sangles de suspension',
  'Rotations russes',
  'Cocon',
  'Hollow hold',
  'Planche de l’ours',
  'Windmill',
  'Planche sur Swiss ball',
  'Rotations du buste avec landmine',
  'Rotation du buste debout à la poulie',
  'Flexions latérales à la poulie basse',
  'Touche talon alternés',
  'Sits-up à la chaise romaine',
  'Planche inversée',
  'Russian twists à la poulie sur Swiss ball',
  'Relevé de jambes assis',
  'Ciseaux',
  'Dead bug',
  'Cercles jambes tendues',
  'Bear plank avec kickback',
  'Planche avec sangles de suspension',
  'Planche latérale avec rotation',
  'Crunch avec jambes verticales',
  'Rotation du buste avec élastique',
  'Planche',
  'Roulage avec une barre',
  'Zercher carry',

];
