export const OPTIONS = [
    { id: 1, name: 'crunch' },
    { id: 2, name: 'pompe' },
    { id: 3, name: 'traction' },
    { id:4, name:'Sit-up décliné' },
    { id:5, name:'Relevé de genoux suspendu' },
    { id:6, name:'Relevé de jambes à la chaise romaine' },
    { id:7, name:'Roulette à abdominaux' },
    { id:8, name:'Relevé de jambes suspendu' },
    { id:9, name:'Crunch à la poulie' },
    { id:10, name:'Flexions des obliques au banc à lombaire à 45°' },
    { id:11, name:'Planche latérale' },
    { id:12, name:'Mountain climber' },
    { id:13, name:'Rotations du buste avec barre' },
    { id:14, name:'Crunch sur swiss ball' },
    { id:15, name:'Rotations des abdominaux suspendu' },
    { id:16, name:'Sit-up avec médecine ball contre un mur' },
    { id:17, name:'Crunch à la machine' },
    { id:18, name:'Dragon flag' },
    { id:19, name:'Flexions latérales avec haltère' },
    { id:20, name:'AB Coaster' },
    { id:21, name:'Crunch debout avec élastique' },
    { id:22, name:'Crunch papillon' },
    { id:23, name:'Crunch bicyclette' },
    { id:24, name:'Jackknife sur swiss ball' },
    { id:25, name:'Crunch avec sangles de suspension' },
    { id:26, name:'Rotations russes' },
    { id:27, name:'Cocon' },
    { id:28, name:'Hollow hold' },
    { id:29, name:'Planche de l’ours' },
    { id:30, name:'Windmill' },
    { id:31, name:'Planche sur Swiss ball' },
    { id:32, name:'Rotations du buste avec landmine' },
    { id:33, name:'Rotation du buste debout à la poulie' },
    { id:34, name:'Flexions latérales à la poulie basse' },
    { id:35, name:'Touche talon alternés' },
    { id:36, name:'Sits-up à la chaise romaine' },
    { id:37, name:'Planche inversée' },
    { id:38, name:'Russian twists à la poulie sur Swiss ball' },
    { id:39, name:'Relevé de jambes assis' },
    { id:40, name:'Ciseaux' },
    { id:41, name:'Dead bug' },
    { id:42, name:'Cercles jambes tendues' },
    { id:43, name:'Bear plank avec kickback' },
    { id:44, name:'Planche avec sangles de suspension' },
    { id:45, name:'Planche latérale avec rotation' },
    { id:46, name:'Crunch avec jambes verticales' },
    { id:47, name:'Rotation du buste avec élastique' },
    { id:48, name:'Planche' },
    { id:49, name:'Roulage avec une barre' },
    { id:50, name:'Zercher carry' },
    

  ];
  